(()=>{
 const U='https://hfczfnaaqwsmvgahiygc.supabase.co',K='sb_publishable_AfyF3k8-uEzorkoYC98D-Q_QRlgkuvS';
 const sb=window.supabase?.createClient(U,K);if(!sb)return;
 const style=document.createElement('style');style.textContent='.vw-panel{position:absolute;inset:10px 10px 90px 10px;background:#101216;border:1px solid #252a31;border-radius:14px;z-index:20;display:none;overflow:auto}.vw-panel.open{display:block}.vw-head{display:flex;justify-content:space-between;align-items:center;padding:14px 16px;border-bottom:1px solid #252a31}.vw-body{padding:16px}.vw-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:10px}.vw-card{border:1px solid #252a31;background:#0d0f12;border-radius:10px;padding:12px}.vw-btn{border:1px solid #303640;background:#171a1f;color:#eee;border-radius:8px;padding:8px 10px}.vw-input{width:100%;background:#0b0d10;color:#eee;border:1px solid #303640;border-radius:8px;padding:9px;margin:5px 0}.vw-code{width:100%;min-height:240px;background:#0a0c0f;color:#dfe5eb;border:1px solid #303640;border-radius:8px;padding:12px;font-family:ui-monospace,monospace;resize:vertical}.vw-row{display:flex;gap:8px;flex-wrap:wrap}';document.head.appendChild(style);
 const panel=document.createElement('section');panel.className='vw-panel';panel.id='vwPanel';panel.innerHTML='<div class="vw-head"><strong id="vwTitle">Workspace</strong><button class="vw-btn" id="vwClose">Close</button></div><div class="vw-body" id="vwBody"></div>';document.querySelector('.chat')?.appendChild(panel);
 const body=panel.querySelector('#vwBody'),title=panel.querySelector('#vwTitle');
 async function me(){return (await sb.auth.getUser()).data.user}
 function close(){panel.classList.remove('open')}
 async function projects(){title.textContent='Projects';const u=await me();if(!u)return;const r=await sb.from('projects').select('id,name,description,updated_at').eq('user_id',u.id).order('updated_at',{ascending:false});body.innerHTML='<div class="vw-row"><button class="vw-btn" id="newProject">+ New project</button></div><div class="vw-grid" id="pg"></div>';const g=body.querySelector('#pg');(r.data||[]).forEach(p=>{const c=document.createElement('div');c.className='vw-card';c.innerHTML='<b></b><p></p><button class="vw-btn openProj">Open</button>';c.querySelector('b').textContent=p.name;c.querySelector('p').textContent=p.description||'';c.querySelector('.openProj').onclick=()=>editor(p);g.appendChild(c)});body.querySelector('#newProject').onclick=async()=>{const n=prompt('Project name');if(!n)return;await sb.from('projects').insert({user_id:u.id,name:n});projects()};panel.classList.add('open')}
 async function editor(p){title.textContent=p.name;const u=await me();const r=await sb.from('project_files').select('id,path,content,language').eq('project_id',p.id).eq('user_id',u.id).order('path');body.innerHTML='<div class="vw-row"><button class="vw-btn" id="newFile">+ New file</button><button class="vw-btn" id="saveFile">Save</button></div><div class="vw-grid"><div class="vw-card"><b>Files</b><div id="fl"></div></div><div class="vw-card"><b>Editor</b><input id="fp" class="vw-input" placeholder="file path"><textarea id="fc" class="vw-code"></textarea></div></div>';const fl=body.querySelector('#fl'),fp=body.querySelector('#fp'),fc=body.querySelector('#fc');(r.data||[]).forEach(f=>{const b=document.createElement('button');b.className='vw-btn';b.textContent=f.path;b.style.display='block';b.style.width='100%';b.style.marginTop='6px';b.onclick=()=>{fp.value=f.path;fc.value=f.content||''};fl.appendChild(b)});body.querySelector('#newFile').onclick=()=>{fp.value='src/new.js';fc.value='';fc.focus()};body.querySelector('#saveFile').onclick=async()=>{const path=fp.value.trim();if(!path)return;await sb.from('project_files').upsert({project_id:p.id,user_id:u.id,path,content:fc.value,language:path.endsWith('.js')?'javascript':path.endsWith('.css')?'css':path.endsWith('.html')?'html':'text',updated_at:new Date().toISOString()},{onConflict:'project_id,path'});alert('Saved')};panel.classList.add('open')}
 async function agents(){title.textContent='Agents';const u=await me();if(!u)return;const r=await sb.from('agents').select('id,name,description,system_prompt,enabled').eq('user_id',u.id).order('created_at',{ascending:false});body.innerHTML='<div class="vw-row"><button class="vw-btn" id="newAgent">+ New agent</button></div><div class="vw-grid" id="ag"></div>';const g=body.querySelector('#ag');(r.data||[]).forEach(a=>{const c=document.createElement('div');c.className='vw-card';c.innerHTML='<b></b><p></p><small></small>';c.querySelector('b').textContent=a.name;c.querySelector('p').textContent=a.description||'No description';c.querySelector('small').textContent=a.enabled?'Enabled':'Disabled';g.appendChild(c)});body.querySelector('#newAgent').onclick=async()=>{const n=prompt('Agent name');if(!n)return;await sb.from('agents').insert({user_id:u.id,name:n,description:'New Virani agent',system_prompt:''});agents()};panel.classList.add('open')}
 document.querySelectorAll('.nav-item,.nav').forEach(el=>{const t=el.textContent||'';if(t.includes('Projects'))el.onclick=projects;if(t.includes('Agents'))el.onclick=agents});panel.querySelector('#vwClose').onclick=close;
})();
